
<?php include "top.phtml";
$accounts=$this->view_data['accounts'];
 ?>
                <section class="content">

                  <div class="box">
                                                  <div class="box-header">
                                                      <h3 class="box-title">اضافة مستخدم جديد</h3>

                                                  </div><!-- /.box-header -->
                                                  <div class="box-body table-responsive">
                                                    <div class="wrapper">


                                                    <b></b>
                                                    <div class="box box-primary">
                                                      <div class="box-header">
                                                          <h3 class="box-title">بينات المستخدم</h3>

                                                      </div><!-- /.box-header -->
                                                      <!-- form start -->
                                                      <form role="form" method='post' action=''>
                                                          <div class="box-body">
                                                              <div class="form-group">
                                                                  <label for="exampleInputEmail1">البريد الالكتروني:</label>
                                                                  <input type="email" value="<?php echo $accounts['email']; ?>" class="form-control" id="exampleInputEmail1" placeholder="ادخل البريد الالكتروني" name="email">
                                                                <?php echo Message::check('email');  ?>
                                                              </div>
                                                              <div class="form-group">
                                                                  <label for="exampleInputEmail1">:اسم المستخدم</label>
                                                                  <input type="text" value="<?php echo $accounts['username']; ?>" class="form-control" id="exampleInputEmail1" placeholder="ادخل اسم المستخدم" name="username">
                                                              <?php echo Message::check('username');  ?>
                                                              </div>
                                                              <div class="form-group">
                                                                  <label for="exampleInputPassword1">كلمة السر:</label>
                                                                  <input type="password" value="<?php echo $accounts['password']; ?>" class="form-control" id="exampleInputPassword1" placeholder="كلمة السر" name="password">
                                                                  <?php echo Message::check('password');  ?>
                                                              </div>
                                                              <div class="form-group">
                                                                  <label for="exampleInputPassword2">تاكيد كلمة السر:</label>
                                                                  <input type="password" value="<?php echo $accounts['password']; ?>" class="form-control" id="exampleInputPassword2" placeholder="تاكيد كلمة السر" name="passwordConfirm">
                                                                  <?php echo Message::check('passwordConfirm');  ?>
                                                              </div>
                                                              <div class="form-group">
                                                            <label for="Select" class="col-sm-2 control-label">نوع المستخدم:</label>

                                                              <select id="Select" class="form-control" name="type">
                                                                <option value="User" <?php  if($accounts['type']=='User')echo 'selected'; ?>>User</option>
                                                                <option value="Admin"<?php  if($accounts['type']=='Admin')echo 'selected'; ?>>Admin</option>
                                                              </select>
                                                              <?php echo Message::check('type');  ?>
                                                          </div>
                                                              <div class="checkbox">

                                                            <label><input type="checkbox" value="1" name="status" <?php  if($accounts['status']==1)echo 'checked'; ?>>تفعيل الحساب</label>
                                                            </div>
                                                                                                                      </div>

                                                          </div><!-- /.box-body -->

                                                          <div class="box-footer">
                                                              <button type="submit" class="btn btn-primary" name="submit"  value="register">اضافة المستخدم</button>
                                                          </div>
                                                      </form>
                                                  </div>
                                                    <br/>

                                                        <div class="push"></div>
                                                    </div>
                                                  </div><!-- /.box-body -->
                                              </div>
                </section><!-- /.content -->

      <?php include "buttom.phtml" ?>
