
<?php include "top.phtml" ;
$comment=$this->view_data['comments'];
?>
                <section class="content">

                  <div class="box">
                                                  <div class="box-header">
                                                      <h3 class="box-title">تحرير التعليق</h3>

                                                  </div><!-- /.box-header -->
                                                  <div class="box-body table-responsive">
                                                    <div class="wrapper">


                                                    <b></b>
                                                    <div class="box box-primary">
                                                      <div class="box-header">
                                                          <h3 class="box-title">بيانات التعليق</h3>

                                                      </div><!-- /.box-header -->
                                                      <!-- form start -->
                                                      <form role="form" method='post' action='' id="newComments">
                                                          <div class="box-body">

                                                              <div class="form-group">
                                                                  <label for="exampleInputEmail1">:رقم المستخدم المعلق</label>
                                                                  <input type="number" value="<?php echo $comment['user_id']; ?>" class="form-control" id="exampleInputEmail1" placeholder="ادخل رقم المستخدم" name="user_id">
                                                                <?php echo Message::check('user_id');  ?>
                                                              </div>
                                                              <div class="form-group">
                                                                  <label for="exampleInputEmail1">:رقم المقال المعلق لة</label>
                                                                  <input type="number" value="<?php echo $comment['news_id']; ?>" class="form-control" id="exampleInputEmail1" placeholder="ادخل رقم المقال" name="news_id">
                                                              <?php echo Message::check('news_id');  ?>
                                                              </div>


                                                              <div class="form-group">
                                                                <label for="materialContactFormName"><h4>المحتوى: *</h4></label>

                                                                   <textarea  name="text_comment" id="textarea" cols="45" rows="10" id="materialContactFormName" class="form-control">
                                                                     <?php echo $comment['text_com']; ?>"
                                                                   </textarea><br><br>


                                                              <?php echo Message::check('text_comment');  ?>
                                                              </div>

                                                                                                                      </div>

                                                          </div><!-- /.box-body -->

                                                          <div class="box-footer">
                                                              <button type="submit" class="btn btn-primary" name="submit"  value="register">اضافة التعليق</button>
                                                          </div>
                                                      </form>
                                                    </div>
                                                  </div>
                                                    <br/>

                                                        <div class="push"></div>
                                                    </div>
                                                  </div><!-- /.box-body -->
                                              </div>
                </section><!-- /.content -->

      <?php include "buttom.phtml" ?>
