<?php include "top.phtml" ?>
                <section class="content">

                  <div class="box">
                                                  <div class="box-header">
                                                      <h3 class="box-title">عرض جميع المقالات والاخبار</h3>
                                                  </div><!-- /.box-header -->
                                                  <div class="box-body table-responsive">
                                                      <div id="example1_wrapper" class="dataTables_wrapper form-inline" role="grid"><div class="row"><div class="col-xs-6"><div id="example1_length" class="dataTables_length"><label><select size="1" name="example1_length" aria-controls="example1"><option value="10" selected="selected">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> سجل او صف لكل صفحة</label></div></div><div class="col-xs-6"><div class="dataTables_filter" id="example1_filter"><label>بحث: <input type="text" aria-controls="example1"></label></div></div></div><table id="example1" class="table table-bordered table-striped dataTable" aria-describedby="example1_info">
                                                          <thead>
                                                              <tr role="row">
                                                                <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending" style="width: 187px;">#ID</th>
                                                                <th class="sorting" role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 272px;">رقم التعليق</th>
                                                                <th class="sorting" role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending" style="width: 253px;">رقم المستخدم</th>
                                                                <th class="sorting" role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" style="width: 160px;">التفاعل</th>

                                                                  <th class="sorting" role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending" style="width: 116px;">الحدث</th>
                                                              </tr>
                                                          </thead>

                                                          <!-- <tfoot>
                                                              <tr><th rowspan="1" colspan="1">Rendering engine</th>
                                                                <th rowspan="1" colspan="1">Browser</th>
                                                                <th rowspan="1" colspan="1">Platform(s)</th>
                                                                <th rowspan="1" colspan="1">Engine version</th>
                                                                <th rowspan="1" colspan="1">CSS grade</th></tr>
                                                          </tfoot> -->
                                                      <tbody role="alert" aria-live="polite" aria-relevant="all">
                                                        <?php
                                                         if (array_key_exists('likes',$this->view_data)){

                                                          $table='';

                                                          foreach ($this->view_data['likes'] as $like) {


                                                                  $table.='<tr class="odd">';
                                                                  $table.=' <td class="  sorting_1">'.$like["id"].'</td>';
                                                                  $table.=' <td class="  ">'.$like["commentId"].'</td>';
                                                                  $table.=' <td class="  ">'.$like["userId"].'</td>';
                                                                  if ($like["likes"]==1) {
                                                                  $table.=' <td class="  ">اعجاب</td>';
                                                                }else {
                                                                  $table.=' <td class="  ">غير معجب</td>';
                                                                }


                                                                  $table.=' <td><a href="/activity/edit/'.$like["id"].'">Edit</a> / <a href="/activity/delete/'.$like["id"].'">Delete</a></td>';
                                                          }


                                                        echo $table;
                                                        }






                                                          ?>


                                                              </tbody></table><div class="row">
                                                                <div class="col-xs-6">
                                                                  <div class="dataTables_info" id="example1_info">
                                                                    Showing 1 to 10 of 57 entries</div></div>
                                                                    <div class="col-xs-6">
                                                                      <div class="dataTables_paginate paging_bootstrap">
                                                                        <ul class="pagination"><li class="prev disabled">
                                                                          <a href="#">← Previous</a></li><li class="active">
                                                                            <a href="#">1</a></li><li><a href="#">2</a></li><li>
                                                                              <a href="#">3</a></li><li><a href="#">4</a></li><li><a href="#">5</a></li><li class="next"><a href="#">Next → </a></li></ul></div></div></div></div>
                                                  </div><!-- /.box-body -->
                                              </div>
                </section><!-- /.content -->

      <?php include "buttom.phtml" ?>
